
import { Dimensions, StyleSheet } from 'react-native';

const WINDOW_WIDTH = Dimensions.get("window").width;
const VISIBLE_WIDTH_PERCENTAGE = 0.4;
const SLIDER_ITEM_WIDTH = WINDOW_WIDTH * VISIBLE_WIDTH_PERCENTAGE;
const { width } = Dimensions.get("window");


export const BaseStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainContainer: {
    flex: 1,
  },

  contentWrapper: {
    flex: 1,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
  section: { paddingVertical: 15 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 6,
  },
  viewAllButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  viewAllButtonText: {
    // color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  sliderContainer: { paddingHorizontal: 15 },
  sliderItem: {
    width: SLIDER_ITEM_WIDTH,
    marginRight: 10,
    borderRadius: 15,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  imageContainer: { height: 130, width: "100%", justifyContent: "flex-end" },
  sliderImage: {
    ...StyleSheet.absoluteFillObject,
    height: "100%",
    width: "100%",
  },
  textOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
    paddingTop: 80,
  },
  textContainer: { padding: 15, zIndex: 10 },
  sliderTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 5,
  },
  sliderDate: {
    fontSize: 12,
    color: "#E0E0E0",
    marginBottom: 5,
    fontWeight: "600",
  },
  quickButtonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 15,
  },
  quickButton: {
    width: "48%",
    height: 120,
    justifyContent: "center",
    alignItems: "flex-start",
    borderRadius: 12,
    marginVertical: 8,
    padding: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    borderLeftWidth: 4,
  },
  iconContainer: {
    marginBottom: 10,
    backgroundColor: "transparent",
    padding: 5,
    borderRadius: 50,
  },
  quickButtonText: { fontWeight: "600", fontSize: 16, textAlign: "left" },
  marginRight: { marginRight: 25 },
  noMargin: { marginRight: 0 },
  flatListContent: {
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  headerFloating: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 10,
  },
  backCircle: {
    width: 45,
    height: 45,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  heroImage: {
    width: "100 %",
    height: 300,
  },
  contentContainer: {
    flex: 1,
    marginTop: -30,
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    paddingHorizontal: 25,
    paddingTop: 30,
  },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 15,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 15,
  },
  badgeText: { fontWeight: "700", fontSize: 12, textTransform: "uppercase" },
  title: { fontSize: 26, fontWeight: "800", marginBottom: 10, lineHeight: 32 },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 25,
    gap: 5,
  },
  dateText: { fontSize: 14, opacity: 0.6 },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    padding: 20,
    borderRadius: 20,
    marginBottom: 30,
  },
  statItem: { alignItems: "center" },
  statValue: { fontSize: 18, fontWeight: "bold" },
  statLabel: { fontSize: 12, opacity: 0.7, marginTop: 4 },
  statDivider: { width: 1, height: "80%" },
  sectionTitle2: { fontSize: 18, fontWeight: "bold", marginBottom: 12 },
  description: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 15,
    lineHeight: 24,
  },
  fullContent: {
    fontSize: 15,
    lineHeight: 26,
    opacity: 0.8,
    textAlign: "justify",
  },
  footerAction: {
    position: "absolute",
    bottom: 0,
    padding: 20,
    backgroundColor: "transparent",
  },
  mainButton: {
    flexDirection: "row",
    height: 60,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  mainButtonText: { color: "#FFF", fontSize: 18, fontWeight: "bold" },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginHorizontal: 10,
    opacity: 0.5,
  },
  readTime: {
    fontSize: 14,
    opacity: 0.6,
  },
  footerdetail: {
    position: "absolute",
    bottom: 0,
    width: width,
    padding: 20,
    borderTopWidth: 1,
  },
  registerButtondetail: {
    height: 55,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
  },
  registerButtonTextdetail: { color: "#FFF", fontSize: 16, fontWeight: "bold" },
});